# Generated by Django 4.1 on 2022-11-22 01:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypePostHelp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_post', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PostHelp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('text', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('type_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.typeposthelp')),
            ],
        ),
    ]
