# Generated by Django 4.1 on 2022-11-22 01:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_posthelp_owner'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PostHelp',
        ),
        migrations.DeleteModel(
            name='TypePostHelp',
        ),
    ]
