# Generated by Django 4.1 on 2022-11-25 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_room_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='owner',
            new_name='user_1',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='title',
            new_name='user_2',
        ),
    ]
