# Generated by Django 4.1 on 2022-11-25 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_rename_owner_room_user_1_rename_title_room_user_2'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='reason',
            field=models.CharField(default=2, max_length=255),
            preserve_default=False,
        ),
    ]
