# Generated by Django 4.1 on 2022-11-28 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0010_privatechat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posthelp',
            name='type_post',
        ),
        migrations.DeleteModel(
            name='TypePostHelp',
        ),
    ]
