# Generated by Django 4.1 on 2022-10-29 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_typearticle_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='link_for_image',
            field=models.CharField(default='https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.jssor.com%2Fdemos%2Fimage-slider.slider&psig=AOvVaw0yLA41bsKX6tX66LWF7k37&ust=1667140785778000&source=images&cd=vfe&ved=0CA0QjRxqFwoTCIDy19zVhfsCFQAAAAAdAAAAABAG', max_length=255),
        ),
    ]
