# Generated by Django 4.1 on 2022-10-29 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_articles_link_for_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articles',
            name='level',
        ),
    ]
