# Generated by Django 4.1 on 2022-10-30 12:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_articles_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='time',
            field=models.DateTimeField(auto_now_add=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comments',
            name='time',
            field=models.DateTimeField(auto_now_add=True),
            preserve_default=False,
        ),
    ]
