# Generated by Django 4.1 on 2022-10-30 12:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_articles_time_comments_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 30, 12, 15, 37, 59477, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='comments',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 30, 12, 15, 37, 59477, tzinfo=datetime.timezone.utc)),
        ),
    ]
