# Generated by Django 4.1 on 2022-10-30 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_articles_time_alter_comments_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='comments',
            name='time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
