# Generated by Django 4.1 on 2022-10-30 12:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_articles_time_alter_comments_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 30, 12, 22, 42, 700970, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='comments',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 30, 12, 22, 42, 700970, tzinfo=datetime.timezone.utc)),
        ),
    ]
