# Generated by Django 4.1.1 on 2022-11-13 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0002_question_lvl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='lvl',
            field=models.CharField(choices=[(1, 'Very good'), (2, 'Really good'), (3, 'Good'), (4, 'Good Enough'), (5, 'Normal'), (6, 'Kind of bad'), (7, 'Bad'), (8, 'Really bad'), (9, 'Very very bad'), (10, 'Extremely bad')], default=0, max_length=20),
        ),
    ]
